basic.showIcon(IconNames.Ghost)
magicbit.rgb().clear()
basic.forever(function () {
    magicbit.rgb().showColor(neopixel.colors(NeoPixelColors.Red))
    magicbit.rgb().show()
    basic.pause(1000)
    magicbit.rgb().clear()
    magicbit.rgb().setPixelColor(0, neopixel.colors(NeoPixelColors.Indigo))
    magicbit.rgb().show()
    basic.pause(1000)
    magicbit.rgb().clear()
    magicbit.rgb().setPixelColor(1, neopixel.colors(NeoPixelColors.Green))
    magicbit.rgb().show()
    basic.pause(1000)
    magicbit.rgb().clear()
    magicbit.rgb().setPixelColor(2, neopixel.colors(NeoPixelColors.Orange))
    magicbit.rgb().show()
    basic.pause(1000)
    magicbit.rgb().clear()
    magicbit.rgb().setPixelColor(3, neopixel.colors(NeoPixelColors.Blue))
    magicbit.rgb().show()
    basic.pause(1000)
    magicbit.rgb().clear()
})
